#!/bin/csh -f

if ( "$1" == "-h" || "$1" == "--help" || "$1" == "" ) then
  echo
  echo "greps: searches psrchive source code for regular expression"
  echo
  echo "usage:"
  echo "  greps <regex>"
  echo
  exit
endif

ack --version >& /dev/null
set ACK_AVAILBLE=$?

if ( "$ACK_AVAILBLE" == "0" ) then
  set GREP_COMMAND=ack
else
  set GREP_COMMAND=grep
endif

$GREP_COMMAND $* `find Util Base More -name "*.[hcC]"`

$GREP_COMMAND $* `find Util Base More -name Makefile.am`

$GREP_COMMAND $* `find Util Base More -name "*.tex"`

