/***************************************************************************
 *
 *   Copyright (C) 2006 by Willem van Straten
 *   Licensed under the Academic Free License version 2.1
 *
 ***************************************************************************/

// #define _DEBUG 1

#include "Pulsar/Config.h"

// This file is generated by configure
#include "Management/psrchive_install.h"

#include "CommandParser.h"

#include <stdlib.h>

#include <iostream>

using namespace std;

// global configuration
Configuration* Pulsar::Config::config = 0;

//
Pulsar::Config::Interface* Pulsar::Config::interface = 0;

void Pulsar::Config::load_config () 
{
  config = new Configuration;

  const char* psrchive_config = getenv ("PSRCHIVE_CONFIG");
  if (psrchive_config) {
#ifdef _DEBUG
    cerr << "Pulsar::Config::load_config $PSRCHIVE_CONFIG=" 
	 << psrchive_config << endl;
#endif
    try {
      config->load( psrchive_config );
    }
    catch (Error& error) {
      // use of a configuration file is optional
#ifdef _DEBUG
      cerr << "Pulsar::Config::load_config error loading " << psrchive_config
	   << " "  << error.get_message() << endl;
#endif
    }
  }
  
  const char* home = getenv ("HOME");
  if (home) {
#ifdef _DEBUG
    cerr << "Pulsar::Config::load_config $HOME=" << home << endl;
#endif
    string home_config = string(home) + "/.psrchive.cfg";

    try {
      config->load( home_config );
    }
    catch (Error& error) {
      // use of a configuration file is optional
#ifdef _DEBUG
      cerr << "Pulsar::Config::load_config error loading " << home_config
	   << " "  << error.get_message() << endl;
#endif
    }
  }

}



string Pulsar::Config::get_runtime ()
{
  return get_home() + "/share";
}

string Pulsar::Config::get_home ()
{
  char* psrchive = getenv ("PSRCHIVE");
  if (psrchive)
    return psrchive;

  return PSRCHIVE_INSTALL;
}

//! Return the configuration key/value pairs
Configuration* Pulsar::Config::get_configuration ()
{
  if (!config)
    load_config ();

#ifdef _DEBUG
  cerr << "Pulsar::Config::get_configuration return " << config << endl;
#endif

  return config;
}

//! Return the text interface to the configuration parameters
Pulsar::Config::Interface* Pulsar::Config::get_interface ()
{
  if (!interface)
    interface = new Interface;

#ifdef _DEBUG
  cerr << "Pulsar::Config::get_interface return " << interface << endl;
#endif

  return interface;
}

