
intermediate-install:
	$(MAKE) RECURSIVE_TARGETS=install-data-recursive INSTALL_DATA=$$PWD/$(top_srcdir)/config/install-intermediate prefix=$$PWD/$(top_builddir) install-data

intermediate-libs:
	AM_MAKEFLAGS="$(AM_MAKEFLAGS) PROGRAMS= HEADERS=" $(MAKE) all-recursive

libs: intermediate-libs intermediate-install install-libLTLIBRARIES

include: install-data

